name: Deploy to GitHub Pages

# Lancia il workflow ad ogni push su master
on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    # Utilizza l'immagine ubuntu-latest su cui far girare gli step
    runs-on: ubuntu-latest
    steps:
    # GitHub checkout action per fare il git checkout dal branch master
    - uses: actions/checkout@v2
    
    # Installazione .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1

    # Publish del progetto Blazor sulla cartella release
    - name: Publish .NET Core Project
      run: dotnet publish -c Release -o release --nologo
    
    #  Cambio tag base in index.html da '/' a 'blog' per riconoscere la sottocartella di GitHub Pages
    - name: Change base-tag in index.html from / to my Repository Name
      run: sed -i 's/<base href="\/" \/>/<base href="\/blog\/" \/>/g' release/wwwroot/index.html
    
    # File 404.html con routing di Blazor
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # Aggiunta di un file .nojekyll per bypassare lo standard di GitHub Pages (Permette file e cartelle che iniziano per underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        BRANCH: gh-pages
        FOLDER: release/wwwroot
